chore: consummate CAPI framework
eesast/THUAI5 pull request #106
Opened 2022-01-13 06:46 UTC by wyj-source

- [ ] 您的代码是否能够编译通过？
- [ ] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI5/pulls) 中是否有与你的贡献功能相同的更改？
- [ ] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI5/blob/dev/CODE_OF_CONDUCT.md)？
- [ ] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI5#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  

Discriptions of this pull request:

接口基本写好。不过还没有进行编译，也还没有debug。
现在和THUAI4的一个较大区别是，THUAI4的CAPI是一整个工程，而THUAI5被划分为了API和Communication部分。那么生成逻辑应该是这样的：先生成一个C++写的communication.lib/dll，再把这个组件放在API下生成可执行文件。但具体怎么做还不大懂。。。
这几天我再研究下linux下的编译、运行方式。

2022-01-13 09:16 UTC, Timothy-LiuXuefeng requested changes
收到。
关于在 MSVC 上如何调用另一个项目的 lib 或 dll，我稍后开辟一个 issue 讨论一下。

2022-01-13 09:16 UTC, Timothy-LiuXuefeng commented on CAPI/API/src/logic.cpp
> +    bool visible(std::shared_ptr<THUAI5::Character> self, const Protobuf::MessageOfCharacter& c)
```suggestion
    static bool visible(std::shared_ptr<THUAI5::Character> self, const Protobuf::MessageOfCharacter& c)
```

2022-01-13 09:16 UTC, Timothy-LiuXuefeng commented on CAPI/API/src/logic.cpp
> +    bool visible(std::shared_ptr<THUAI5::Character> self, const Protobuf::MessageOfBullet& b)
```suggestion
    static bool visible(std::shared_ptr<THUAI5::Character> self, const Protobuf::MessageOfBullet& b)
```

2022-01-13 09:16 UTC, Timothy-LiuXuefeng commented on CAPI/API/src/logic.cpp
> +    bool visible(std::shared_ptr<THUAI5::Character> self, const Protobuf::MessageOfProp& p)
```suggestion
    static bool visible(std::shared_ptr<THUAI5::Character> self, const Protobuf::MessageOfProp& p)
```

2022-01-13 09:16 UTC, Timothy-LiuXuefeng commented on CAPI/API/src/logic.cpp
> +    return counter_state;
这里存在数据竞争，对 `counter_state` 的访问既不是原子的，又没有加锁

2022-01-13 09:16 UTC, Timothy-LiuXuefeng commented on CAPI/API/src/logic.cpp
> +        pthread_cancel(tAI.native_gandle());
与杀进程不同，从外部杀线程是一个非常危险的操作，以致于很多语言不会提供杀线程的接口（例如 .NET 已经废弃了杀线程的接口，现在该接口只会抛出异常）。例如，线程可能做某件事情做到一半便被杀死，导致一部分数据无效；更糟糕的是，线程的资源不归进程管理，如果线程加了锁但是没有解锁便被杀掉，那么还可能造成死锁等问题。正常方法大概有以下两种：

1. 通过线程间通信方式，让该线程自己正常退出；
2. 让线程一直运行，与进程一同被操作系统杀掉（C++ 需要将 `std::thread` 进行 `detach` 操作）。但是这种做法在 C++ 中存在很大的问题，尤其是可能对象的生命周期结束了，该线程还在通过指针访问该对象，需要特别注意生命周期的管理（尤见于 `this` 指针成为悬垂指针的问题）。

2022-01-13 09:16 UTC, Timothy-LiuXuefeng commented on CAPI/API/src/logic.cpp
>          cv_ai.wait(lock, [this]() {return AI_start; }); // 突然发现此处不能返回atomic_bool类型，所以THUAI4才会搞出另一个控制AI是否启动的标志值
看到这里的注释顺便说一下，这里倒不是不能原子，只需要 `cv_ai.wait(lock, [this]() -> bool { return AI_start; });` 或者 `cv_ai.wait(lock, [this]() { return static_case<bool>(AI_start); });` 就可以了。不过这样做没什么意义，用普通的 `bool` 就可以了。如果原子变量支持 `wait` 操作，那么也不需要 `mutex` 和条件变量了（对原子变量的 `wait` 操作需要 C++20）。
```suggestion
        cv_ai.wait(lock, [this]() { return AI_start; });
```

2022-01-13 09:16 UTC, Timothy-LiuXuefeng commented on CAPI/API/src/logic.cpp
> +    current_state_accessed = false;
对于 `logic.cpp` 有一些问题。
首先是 `AI_execute`，下面开启线程时使用 `tAI = std::thread(AI_execute);`，这只是执行了一次 AI 代码。根据 THUAI4 的代码，大概是忘记了使用 `PlayerWrapper`？
然后是关于缓冲区更新的问题。在调用 AI 代码时，每次都会加上 `mtx_state` 锁：

```cpp
std::lock_guard<std::mutex> lock_state(mtx_state);
if (!current_state_accessed)
{
    current_state_accessed = true;
    pAI->play(*pAPI);
}
else
{
    std::unique_lock<std::mutex> lock_buffer(mtx_buffer);
    cv_buffer.wait(lock_buffer, [this]() {return buffer_updated; });
    Update();
}
```

但是当消息到来时，更新 `pState` 的条件却是获取 `mtx_state` 锁：

```cpp
if (mtx_state.try_lock())
{
    Update();
    mtx_state.unlock();
}
```

那么此接口便是在一次 `play` 调用期间，选手获取到的消息不会改变了。如果采用这种接口，那么只需要一个锁 `mtx_buffer` 便可以达到目的，`mtx_state` 是多余的；如果要使用在一次 `play` 调用期间信息改变，需要另外的设计。关于这两种接口如何设计，稍后我开一个单独的 issue 讨论一下。

2022-01-13 14:16 UTC, wyj-source commented on CAPI/API/src/logic.cpp
> +        pthread_cancel(tAI.native_gandle());
这一个地方的确是在模仿THUAI4。THUAI4的注释中也指出这种强制杀线程的方法不太好，但同时又指出“服务器上跑直接就把 player 线程杀死，防止某些选手的代码是死循环不能正常退出”，算是一种无奈之举。
另外，这个操作用到了<pthread.h>，可否用c++11下的线程库解决这一问题？

2022-01-13 14:22 UTC, wyj-source commented on CAPI/API/src/logic.cpp
> +    current_state_accessed = false;
目前只实现了“一次 play 调用期间，选手获取到的消息不会改变”的接口。至于另外一种接口，打算先看看第一种的效果如何，以后再写。

2022-01-17 13:06 UTC, Timothy-LiuXuefeng approved these changes

2022-01-17 13:06 UTC, merged