chore: finish basic frame work of CAPI
eesast/THUAI5 pull request #98
Opened 2021-12-15 16:41 UTC by wyj-source

- [ ] 您的代码是否能够编译通过？
- [ ] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI5/pulls) 中是否有与你的贡献功能相同的更改？
- [ ] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI5/blob/dev/CODE_OF_CONDUCT.md)？
- [ ] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI5#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  

Discriptions of this pull request:

No additional discription.

2021-12-15 16:46 UTC, wyj-source commented
小结：大致搭好了总体框架，最大的改动是用所谓‘建造者模式’，将对象的构建和logic的执行过程进行了分离（我感觉我写得十分混乱，欢迎指教orz），其它的线程处理之类好像和THUAI4之类的差不多。实际上，还有一些细节比如视野的判定，墙的构造等还在和逻辑组商量，没有写。
这只是最初版本，以后慢慢重构吧。。。

2021-12-15 17:22 UTC, Timothy-LiuXuefeng commented
Got it! 我大致看看代码

2021-12-15 18:33 UTC, Timothy-LiuXuefeng commented
大致看到了一些设计上的问题，等我整理一下，想想解决方案

2021-12-15 20:11 UTC, Timothy-LiuXuefeng requested changes

2021-12-15 20:11 UTC, Timothy-LiuXuefeng commented on CAPI/API/src/logic.cpp
> +    pLogicInterface = std::make_shared<LogicInterface>(SendInfo, Empty, GetInfo, GetCounter, WaitThread, pState);
Logic、API、AI 之间的关系这里的设计可能是最令人头疼的地方了。由于 AI、API、Logic 在逻辑上存在相互之间的依赖关系，因此容易混杂不清。THUAI4 中出现了大量的回调机制就是逻辑上相互依赖导致的结果。目前使用建造者模式虽然有所缓解，但是仍然没有解决本质的问题。主要存在的问题有：

+ `LogicInterface` 的成员依赖于 `logic` 的生命周期，即外部的 `logic` 生命周期不可控，一旦 `logic` 的生命周期先于 `LogicInterface` 的生命期结束，那么再调用 `LogicInterface` 的成员将产生未定义行为，这增加了保证生命期顺序的包袱。

+ 仍然存在众多的回调函数作为参数，可读性仍然较低

+ ……

鉴于此，可以考虑转换依赖关系。关于个人的建议，我稍后单独开辟一条 issue。

2021-12-17 03:53 UTC, TCL606 submitted a review, later dismissed

2021-12-18 07:50 UTC, wyj-source commented
这次摒弃了THUAI4的回调函数写法和之前的建造者模式写法，全部使用DIP写法，同时将用户接口改为线程安全。
至于运行过程中的线程调度，我再好好考虑下怎么写更合理。

2021-12-18 10:41 UTC, Timothy-LiuXuefeng approved these changes

2021-12-18 10:41 UTC, Timothy-LiuXuefeng commented on CAPI/API/include/API.h
> +    ILogic& logic;
其实 `IAPI` 作为接口的话，描述行为大概就够了，给它设置成员和构造函数的意义并不是很大。不过这样写应该也可以吧

2021-12-18 10:41 UTC, Timothy-LiuXuefeng commented on CAPI/API/include/logic.h
> +#define MESSAGE_OF_PROP 3
这个宏如果别的地方没有用过的话，定义在 cpp 里作为内部实现大概就够了？

2021-12-18 13:45 UTC, merged